# Generated by Django 4.0.1 on 2022-02-08 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 16, 17, 1, 38750)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(max_length=200),
        ),
    ]
